# API Keys (replace with your own keys)
GEMINI_API_KEY = "your_gemini_api_key_here"
OPENWEATHER_API_KEY = "your_openweather_api_key_here"
EMAIL_ADDRESS = "your_email_address_here"
EMAIL_PASSWORD = "your_email_password_here"
TWITTER_API_KEY = "your_twitter_api_key_here"
TWITTER_API_SECRET = "your_twitter_api_secret_here"
TWITTER_ACCESS_TOKEN = "your_twitter_access_token_here"
TWITTER_ACCESS_TOKEN_SECRET = "your_twitter_access_token_secret_here"
NEWS_API_KEY = "your_news_api_key_here"
YOUTUBE_API_KEY = "your_youtube_api_key_here"